
site_name: Rambros Handbook

theme:
    name: readthedocs   
    site_description: Help & FAQ     
    highlightjs: true
    hljs_languages:
        - yaml
        - arduino
        - openscad
    logo: logo/rambros-logo.svg
nav:
    - Home: 'index.md'
    - Hardware: 'hardware.md'
    - Blheli_S: 'blheli.md'
    - About: 'index.md'
markdown_extensions:
    - pymdownx.betterem
    - pymdownx.superfences
    - markdown.extensions.footnotes
    - markdown.extensions.attr_list
    - markdown.extensions.def_list
    - markdown.extensions.tables
    - markdown.extensions.abbr
    - markdown.extensions.md_in_html
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.saneheaders
    - pymdownx.tabbed
    - toc:
        permalink: true
        toc_depth: 2
plugins:
    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom


  

